---
Name: toastconfig
After: 'framework/*','cms/*'
---
SiteConfig:
  extensions:
    - ToastConfig
    - AbandonedCartConfig
    - SignUpModalConfig
    - CheckoutStepConfig

Order:
  extensions:
    - ToastCartExtension

Injector:
  CheckoutComponentConfig:
    class: ToastCheckoutComponentConfig

OrdersAdmin:
  managed_models:
    - Order
    - OrderStatusLog
    - SignUpMessage
  extensions:
    - ToastOrdersAdmin

CheckoutComponent:
  extensions:
    - ToastCheckoutComponentExtension

Address:
  extensions:
    - ToastAddressExtension

ShippingAddressCheckoutComponent:
  extensions:
    - ToastAddressComponentExtension

ToastCheckoutComponentConfig:
  formfielddescriptions: false
