---
Name: toastconfig
After: 'framework/*','cms/*'
---
Injector:
  CheckoutComponentConfig:
    class: ToastCheckoutComponentConfig

OrdersAdmin:
  managed_models:
    - Order
    - OrderStatusLog
    - SignUpMessage

ToastCheckoutComponentConfig:
  formfielddescriptions: false

