---
Name: toastconfig
After: 'framework/*','cms/*'
---
SiteConfig:
  extensions:
    - ToastConfig
    - AbandonedCartConfig
    - SignUpModalConfig
    - CheckoutStepConfig

Order:
  extensions:
    - ToastCartExtension

Controller:
  extensions:
    - ToastCheckoutExtension
