---
Name: toastconfig
After: 'framework/*','cms/*','shoproutes/*','shopconfig/*'
---
Injector:
  CheckoutComponentConfig:
    class: ToastCheckoutComponentConfig

OrdersAdmin:
  managed_models:
    - Order
    - OrderStatusLog
    - SignUpMessage

ToastCheckoutComponentConfig:
  formfielddescriptions: false

Order:
  reference_prefix: ''
