---
Name: toastconfig
After: 'framework/*','cms/*'
---
SiteConfig:
  extensions:
    - ToastConfig
    - AbandonedCartConfig
    - SignUpModalConfig
    - CheckoutStepConfig

Order:
  extensions:
    - ToastCartExtension

Injector:
  CheckoutComponentConfig:
    class: ToastCheckoutComponentConfig

OrdersAdmin:
  managed_models:
    - Order
    - OrderStatusLog
    - SignUpMessage
  extensions:
    - ToastOrdersAdmin
